-- AlterTable
ALTER TABLE `quizzes` ADD COLUMN `end_date` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `publishedAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `start_date` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
